[2024-01-28T11:15:41.270+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: jeniferhdfs.submit_spark_job manual__2024-01-28T10:09:10.828594+00:00 [queued]>
[2024-01-28T11:15:41.292+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: jeniferhdfs.submit_spark_job manual__2024-01-28T10:09:10.828594+00:00 [queued]>
[2024-01-28T11:15:41.294+0100] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-01-28T11:15:41.465+0100] {taskinstance.py:2192} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2024-01-28 10:09:10.828594+00:00
[2024-01-28T11:15:41.480+0100] {standard_task_runner.py:60} INFO - Started process 19324 to run task
[2024-01-28T11:15:41.561+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'jeniferhdfs', 'submit_spark_job', 'manual__2024-01-28T10:09:10.828594+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/hdfsDag.py', '--cfg-path', '/tmp/tmprmj2b8rk']
[2024-01-28T11:15:41.578+0100] {standard_task_runner.py:88} INFO - Job 55: Subtask submit_spark_job
[2024-01-28T11:15:41.913+0100] {task_command.py:423} INFO - Running <TaskInstance: jeniferhdfs.submit_spark_job manual__2024-01-28T10:09:10.828594+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-28T11:15:42.379+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jenifer' AIRFLOW_CTX_DAG_ID='jeniferhdfs' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-01-28T10:09:10.828594+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-28T10:09:10.828594+00:00'
[2024-01-28T11:15:42.407+0100] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-28T11:15:42.413+0100] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --name your_spark_job --class main.scala.mnm.MnMcount --verbose --queue root.default hdfs://localhost:9000/user/project/datalake/main-scala-mnm_2.12-1.0.jar
[2024-01-28T11:16:49.913+0100] {spark_submit.py:571} INFO - Using properties file: null
[2024-01-28T11:16:50.576+0100] {spark_submit.py:571} INFO - 24/01/28 11:16:50 WARN Utils: Your hostname, ubuntu resolves to a loopback address: 127.0.1.1; using 10.0.2.15 instead (on interface enp0s3)
[2024-01-28T11:16:50.699+0100] {spark_submit.py:571} INFO - 24/01/28 11:16:50 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-01-28T11:16:51.052+0100] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-01-28T11:16:51.078+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2024-01-28T11:16:51.120+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2024-01-28T11:16:51.145+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2024-01-28T11:16:51.146+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2024-01-28T11:16:51.147+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1055)
[2024-01-28T11:16:51.149+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1055)
[2024-01-28T11:16:51.150+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2024-01-28T11:16:51.150+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1072)
[2024-01-28T11:16:51.151+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1081)
[2024-01-28T11:16:51.152+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-01-28T11:16:51.356+0100] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name your_spark_job --class main.scala.mnm.MnMcount --verbose --queue root.default hdfs://localhost:9000/user/project/datalake/main-scala-mnm_2.12-1.0.jar. Error code is: 1.
[2024-01-28T11:16:51.490+0100] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=jeniferhdfs, task_id=submit_spark_job, execution_date=20240128T100910, start_date=20240128T101541, end_date=20240128T101651
[2024-01-28T11:16:51.921+0100] {standard_task_runner.py:107} ERROR - Failed to execute job 55 for task submit_spark_job (Cannot execute: spark-submit --master yarn --name your_spark_job --class main.scala.mnm.MnMcount --verbose --queue root.default hdfs://localhost:9000/user/project/datalake/main-scala-mnm_2.12-1.0.jar. Error code is: 1.; 19324)
[2024-01-28T11:16:51.974+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-28T11:16:52.038+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
