[2024-01-30T15:57:49.765+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: jeniferhdfs.submit_spark_job manual__2024-01-30T14:57:00.401772+00:00 [queued]>
[2024-01-30T15:57:49.784+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: jeniferhdfs.submit_spark_job manual__2024-01-30T14:57:00.401772+00:00 [queued]>
[2024-01-30T15:57:49.785+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-30T15:57:49.869+0100] {taskinstance.py:2192} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2024-01-30 14:57:00.401772+00:00
[2024-01-30T15:57:49.883+0100] {standard_task_runner.py:60} INFO - Started process 6661 to run task
[2024-01-30T15:57:49.906+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'jeniferhdfs', 'submit_spark_job', 'manual__2024-01-30T14:57:00.401772+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/hdfsDag.py', '--cfg-path', '/tmp/tmpp8gyipkm']
[2024-01-30T15:57:49.910+0100] {standard_task_runner.py:88} INFO - Job 100: Subtask submit_spark_job
[2024-01-30T15:57:50.016+0100] {task_command.py:423} INFO - Running <TaskInstance: jeniferhdfs.submit_spark_job manual__2024-01-30T14:57:00.401772+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-30T15:57:50.342+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jenifer' AIRFLOW_CTX_DAG_ID='jeniferhdfs' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-01-30T14:57:00.401772+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-30T14:57:00.401772+00:00'
[2024-01-30T15:57:50.382+0100] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-30T15:57:50.414+0100] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master local["*"] --conf spark.master=local[*] --conf spark.yarn.conf.dir=/usr/local/hadoop/etc/hadoop --name your_spark_job --class main.scala.mnm.MnMcount --queue root.default --deploy-mode client hdfs://localhost:9000/user/project/datalake/main-scala-mnm_2.12-1.0.jar
[2024-01-30T15:58:12.263+0100] {spark_submit.py:571} INFO - 24/01/30 15:58:12 WARN Utils: Your hostname, ubuntu resolves to a loopback address: 127.0.1.1; using 10.0.2.15 instead (on interface enp0s3)
[2024-01-30T15:58:12.278+0100] {spark_submit.py:571} INFO - 24/01/30 15:58:12 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-01-30T15:58:16.697+0100] {spark_submit.py:571} INFO - 24/01/30 15:58:16 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-01-30T15:58:26.314+0100] {spark_submit.py:571} INFO - Exception in thread "main" java.net.ConnectException: Call From ubuntu/127.0.1.1 to localhost:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[2024-01-30T15:58:26.359+0100] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-01-30T15:58:26.360+0100] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2024-01-30T15:58:26.361+0100] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-01-30T15:58:26.367+0100] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2024-01-30T15:58:26.367+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2024-01-30T15:58:26.368+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:828)
[2024-01-30T15:58:26.374+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1616)
[2024-01-30T15:58:26.375+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2024-01-30T15:58:26.375+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2024-01-30T15:58:26.375+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2024-01-30T15:58:26.376+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2024-01-30T15:58:26.376+0100] {spark_submit.py:571} INFO - at com.sun.proxy.$Proxy27.getFileInfo(Unknown Source)
[2024-01-30T15:58:26.377+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:965)
[2024-01-30T15:58:26.377+0100] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-01-30T15:58:26.377+0100] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-01-30T15:58:26.377+0100] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-01-30T15:58:26.378+0100] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2024-01-30T15:58:26.378+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2024-01-30T15:58:26.378+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2024-01-30T15:58:26.378+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2024-01-30T15:58:26.378+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2024-01-30T15:58:26.379+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2024-01-30T15:58:26.379+0100] {spark_submit.py:571} INFO - at com.sun.proxy.$Proxy28.getFileInfo(Unknown Source)
[2024-01-30T15:58:26.379+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1739)
[2024-01-30T15:58:26.379+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1753)
[2024-01-30T15:58:26.379+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1750)
[2024-01-30T15:58:26.380+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2024-01-30T15:58:26.380+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1765)
[2024-01-30T15:58:26.380+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.fs.FileSystem.isFile(FileSystem.java:1794)
[2024-01-30T15:58:26.380+0100] {spark_submit.py:571} INFO - at org.apache.spark.util.Utils$.fetchHcfsFile(Utils.scala:843)
[2024-01-30T15:58:26.380+0100] {spark_submit.py:571} INFO - at org.apache.spark.util.Utils$.doFetchFile(Utils.scala:820)
[2024-01-30T15:58:26.381+0100] {spark_submit.py:571} INFO - at org.apache.spark.util.DependencyUtils$.downloadFile(DependencyUtils.scala:264)
[2024-01-30T15:58:26.381+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.$anonfun$prepareSubmitEnvironment$8(SparkSubmit.scala:391)
[2024-01-30T15:58:26.381+0100] {spark_submit.py:571} INFO - at scala.Option.map(Option.scala:230)
[2024-01-30T15:58:26.381+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:391)
[2024-01-30T15:58:26.381+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:923)
[2024-01-30T15:58:26.382+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:191)
[2024-01-30T15:58:26.382+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:214)
[2024-01-30T15:58:26.382+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2024-01-30T15:58:26.383+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1072)
[2024-01-30T15:58:26.383+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1081)
[2024-01-30T15:58:26.383+0100] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-01-30T15:58:26.383+0100] {spark_submit.py:571} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-01-30T15:58:26.384+0100] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[2024-01-30T15:58:26.384+0100] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
[2024-01-30T15:58:26.384+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:205)
[2024-01-30T15:58:26.384+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:586)
[2024-01-30T15:58:26.384+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:711)
[2024-01-30T15:58:26.385+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:833)
[2024-01-30T15:58:26.385+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
[2024-01-30T15:58:26.385+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
[2024-01-30T15:58:26.385+0100] {spark_submit.py:571} INFO - at org.apache.hadoop.ipc.Client.call(Client.java:1502)
[2024-01-30T15:58:26.386+0100] {spark_submit.py:571} INFO - ... 34 more
[2024-01-30T15:58:27.482+0100] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master local["*"] --conf spark.master=local[*] --conf spark.yarn.conf.dir=/usr/local/hadoop/etc/hadoop --name your_spark_job --class main.scala.mnm.MnMcount --queue root.default --deploy-mode client hdfs://localhost:9000/user/project/datalake/main-scala-mnm_2.12-1.0.jar. Error code is: 1.
[2024-01-30T15:58:27.539+0100] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=jeniferhdfs, task_id=submit_spark_job, execution_date=20240130T145700, start_date=20240130T145749, end_date=20240130T145827
[2024-01-30T15:58:27.804+0100] {standard_task_runner.py:107} ERROR - Failed to execute job 100 for task submit_spark_job (Cannot execute: spark-submit --master local["*"] --conf spark.master=local[*] --conf spark.yarn.conf.dir=/usr/local/hadoop/etc/hadoop --name your_spark_job --class main.scala.mnm.MnMcount --queue root.default --deploy-mode client hdfs://localhost:9000/user/project/datalake/main-scala-mnm_2.12-1.0.jar. Error code is: 1.; 6661)
[2024-01-30T15:58:27.877+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-30T15:58:27.982+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
